import React, { useState } from 'react';
import { 
  Stethoscope, 
  User, 
  Clock, 
  CheckCircle2, 
  FileText, 
  AlertCircle, 
  Pill, 
  Share2, 
  Hospital, 
  Send,
  Sparkles,
  ChevronRight,
  ShieldCheck,
  Ambulance
} from 'lucide-react';
import { MOCK_DOCTORS, MOCK_MEDICINES } from '../../data/mockData';
import { audioService } from '../../utils/audioUtils';

export default function DoctorDashboard({ 
  appointments, 
  onGenerateReferral, 
  onCompleteAppointment 
}) {
  const [selectedDoctor, setSelectedDoctor] = useState(MOCK_DOCTORS[0]);
  const [activePatient, setActivePatient] = useState(appointments[0] || null);
  const [clinicalDiagnosis, setClinicalDiagnosis] = useState('');
  const [selectedMedicines, setSelectedMedicines] = useState(['Paracetamol 500mg (1 TDS x 3 days)']);
  const [isReferring, setIsReferring] = useState(false);
  const [referralTarget, setReferralTarget] = useState('CHC Mawana');
  const [referralSpecialty, setReferralSpecialty] = useState('Internal Medicine');
  const [referralUrgency, setReferralUrgency] = useState('Urgent');

  const handleSelectPatient = (apt) => {
    setActivePatient(apt);
    setClinicalDiagnosis(`Acute presentation for ${apt.symptoms}`);
    setIsReferring(false);
  };

  const handleSaveConsultation = () => {
    if (!activePatient) return;
    audioService.playNotificationSound();
    alert(`Consultation completed for ${activePatient.patientName}. Digital E-Prescription synced to ABHA.`);
  };

  const handleIssueReferral = () => {
    if (!activePatient) return;
    const refId = `REF-2026-${Math.floor(1000 + Math.random() * 9000)}`;

    const newRef = {
      serviceId: refId,
      patientName: activePatient.patientName,
      age: 42,
      gender: 'Male',
      abhaId: activePatient.abhaId,
      phone: activePatient.phone,
      fromFacility: selectedDoctor.facilityName,
      toFacility: referralTarget,
      referringDoctor: selectedDoctor.name,
      specialistRequired: referralSpecialty,
      urgency: referralUrgency,
      dateInitiated: new Date().toISOString().split('T')[0],
      status: 'Bed Reserved / Transfer Requested',
      transportType: '108 Ambulance Alerted',
      notes: `Referred by ${selectedDoctor.name}: ${clinicalDiagnosis || activePatient.symptoms}`,
      timeline: [
        { time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), text: `Referral generated by ${selectedDoctor.name}` },
        { time: 'Next', text: `Bed reserved at ${referralTarget}` }
      ]
    };

    if (onGenerateReferral) {
      onGenerateReferral(newRef);
    }
    audioService.playNotificationSound();
    setIsReferring(false);
    alert(`Digital Referral ${refId} issued successfully! Bed reserved at ${referralTarget} and SMS sent to patient.`);
  };

  return (
    <div className="space-y-6">
      {/* Top Doctor Profile Bar */}
      <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center space-x-4">
          <img 
            src={selectedDoctor.avatar} 
            alt={selectedDoctor.name} 
            className="w-14 h-14 rounded-2xl object-cover border-2 border-emerald-500 shadow-sm"
          />
          <div>
            <div className="flex items-center space-x-2">
              <h2 className="text-lg font-extrabold text-slate-900">{selectedDoctor.name}</h2>
              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-100 text-emerald-800">
                Medical Officer On Duty
              </span>
            </div>
            <p className="text-xs text-slate-500">
              {selectedDoctor.qualification} • {selectedDoctor.specialty} • <strong className="text-slate-700">{selectedDoctor.facilityName}</strong>
            </p>
          </div>
        </div>

        {/* Doctor Switcher & Stats */}
        <div className="flex items-center space-x-3 text-xs">
          <div className="p-2.5 bg-slate-50 rounded-xl border border-slate-200 text-center">
            <span className="text-[10px] text-slate-500 font-medium block">Today's Queue</span>
            <span className="font-extrabold text-sm text-emerald-700">{appointments.length} Patients</span>
          </div>

          <select
            value={selectedDoctor.id}
            onChange={(e) => {
              const doc = MOCK_DOCTORS.find(d => d.id === e.target.value);
              if (doc) setSelectedDoctor(doc);
            }}
            className="bg-slate-100 border border-slate-300 rounded-xl px-3 py-2 text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-500"
          >
            {MOCK_DOCTORS.map(d => (
              <option key={d.id} value={d.id}>{d.name} ({d.facilityName})</option>
            ))}
          </select>
        </div>
      </div>

      {/* Main Clinical Consultation Workspace */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Left: Patient Queue */}
        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-slate-200">
            <div>
              <h3 className="font-bold text-sm text-slate-900">OPD Patient Queue</h3>
              <p className="text-[11px] text-slate-500">Synced across IVR, SMS & Web channels</p>
            </div>
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800">
              Live
            </span>
          </div>

          <div className="space-y-2.5">
            {appointments.map((apt) => {
              const isSelected = activePatient?.id === apt.id;
              return (
                <div
                  key={apt.id}
                  onClick={() => handleSelectPatient(apt)}
                  className={`p-3 rounded-xl border cursor-pointer transition-all ${
                    isSelected
                      ? 'border-emerald-500 bg-emerald-50/70 shadow-xs ring-1 ring-emerald-500'
                      : 'border-slate-200 hover:border-slate-300 bg-white'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-bold text-xs text-slate-900">{apt.patientName}</span>
                    <span className="font-mono text-[10px] bg-slate-900 text-white px-1.5 py-0.2 rounded">
                      {apt.serviceId}
                    </span>
                  </div>

                  <div className="text-[11px] text-slate-600 line-clamp-1">
                    {apt.symptoms}
                  </div>

                  <div className="flex items-center justify-between text-[10px] text-slate-500 mt-2 pt-1.5 border-t border-slate-100">
                    <span className="font-medium text-emerald-700">{apt.channel}</span>
                    <span>{apt.timeSlot}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Center & Right: Clinical Consultation & Digital Referral Desk */}
        <div className="lg:col-span-2 bg-white rounded-2xl border border-slate-200 p-5 shadow-sm space-y-5">
          {activePatient ? (
            <div className="space-y-5">
              {/* Patient Banner */}
              <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div>
                  <div className="flex items-center space-x-2">
                    <h4 className="font-extrabold text-base text-slate-900">{activePatient.patientName}</h4>
                    <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-purple-100 text-purple-800 font-bold">
                      ABHA: {activePatient.abhaId}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Phone: {activePatient.phone} • Booked via: <strong className="text-emerald-700">{activePatient.channel}</strong>
                  </p>
                </div>

                <div className="flex items-center space-x-2">
                  <span className="text-xs text-slate-500">Primary Complaint:</span>
                  <span className="px-2.5 py-1 rounded-lg bg-amber-100 text-amber-900 text-xs font-bold">
                    {activePatient.symptoms}
                  </span>
                </div>
              </div>

              {/* Clinical Notes & Vitals */}
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1.5">
                  Doctor Clinical Examination & Diagnosis Notes:
                </label>
                <textarea
                  rows={3}
                  value={clinicalDiagnosis}
                  onChange={(e) => setClinicalDiagnosis(e.target.value)}
                  placeholder="Record patient vitals (BP, SpO2, Temp), provisional diagnosis, and advice..."
                  className="w-full p-3 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-800 focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              {/* E-Prescription Form */}
              <div className="p-4 bg-emerald-50/50 rounded-xl border border-emerald-200 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <Pill className="w-4 h-4 text-emerald-700" />
                    <span className="font-bold text-xs text-emerald-900">Digital E-Prescription (Jan Aushadhi Linked)</span>
                  </div>
                  <span className="text-[10px] font-semibold text-emerald-700">Dispensed free at PHC Pharmacy</span>
                </div>

                <div className="space-y-1.5">
                  {selectedMedicines.map((m, idx) => (
                    <div key={idx} className="flex items-center justify-between bg-white p-2 rounded-lg border border-emerald-200 text-xs">
                      <span className="font-medium text-slate-800">{m}</span>
                      <button
                        onClick={() => setSelectedMedicines(selectedMedicines.filter((_, i) => i !== idx))}
                        className="text-rose-600 hover:text-rose-800 text-xs font-bold"
                      >
                        ✕
                      </button>
                    </div>
                  ))}
                </div>

                <div className="flex gap-2">
                  <select
                    id="med-select-box"
                    className="flex-1 bg-white border border-emerald-300 rounded-lg px-2.5 py-1.5 text-xs text-slate-800"
                  >
                    {MOCK_MEDICINES.filter(m => m.stockStatus !== 'Out of Stock').map(m => (
                      <option key={m.id} value={`${m.name} (${m.category})`}>
                        {m.name} - In Stock ({m.totalQuantity})
                      </option>
                    ))}
                  </select>
                  <button
                    type="button"
                    onClick={() => {
                      const select = document.getElementById('med-select-box');
                      if (select && select.value) {
                        setSelectedMedicines([...selectedMedicines, select.value]);
                      }
                    }}
                    className="px-3 py-1.5 bg-emerald-700 hover:bg-emerald-800 text-white rounded-lg text-xs font-bold transition-colors"
                  >
                    + Add Drug
                  </button>
                </div>
              </div>

              {/* Referral Escalation Drawer */}
              {isReferring ? (
                <div className="p-4 bg-purple-50 rounded-xl border-2 border-purple-300 space-y-3 animate-fadeIn">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <Hospital className="w-4 h-4 text-purple-700" />
                      <span className="font-bold text-xs text-purple-950">Issue Digital Referral & Bed Reservation</span>
                    </div>
                    <button 
                      onClick={() => setIsReferring(false)}
                      className="text-xs font-bold text-purple-700 hover:underline"
                    >
                      Cancel
                    </button>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                    <div>
                      <label className="block text-[11px] font-semibold text-purple-900 mb-1">Target Facility:</label>
                      <select
                        value={referralTarget}
                        onChange={(e) => setReferralTarget(e.target.value)}
                        className="w-full bg-white border border-purple-300 rounded-lg p-2 text-xs"
                      >
                        <option value="CHC Mawana">CHC Mawana (Secondary)</option>
                        <option value="District Hospital Meerut">District Hospital Meerut (Tertiary)</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-[11px] font-semibold text-purple-900 mb-1">Specialty Needed:</label>
                      <select
                        value={referralSpecialty}
                        onChange={(e) => setReferralSpecialty(e.target.value)}
                        className="w-full bg-white border border-purple-300 rounded-lg p-2 text-xs"
                      >
                        <option value="Cardiology">Cardiology</option>
                        <option value="Obstetrics / High-Risk ANC">Obstetrics / High-Risk ANC</option>
                        <option value="Internal Medicine">Internal Medicine</option>
                        <option value="Orthopaedics & Trauma">Orthopaedics & Trauma</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-[11px] font-semibold text-purple-900 mb-1">Urgency Level:</label>
                      <select
                        value={referralUrgency}
                        onChange={(e) => setReferralUrgency(e.target.value)}
                        className="w-full bg-white border border-purple-300 rounded-lg p-2 text-xs font-bold"
                      >
                        <option value="Urgent">Urgent (Within 4 hrs)</option>
                        <option value="Emergency (108 ALS)">Emergency (108 ALS Ambulance)</option>
                        <option value="Routine">Routine (Next OPD)</option>
                      </select>
                    </div>
                  </div>

                  <button
                    onClick={handleIssueReferral}
                    className="w-full py-2.5 bg-purple-700 hover:bg-purple-800 text-white font-bold text-xs rounded-xl flex items-center justify-center space-x-2 shadow-md shadow-purple-900/20 transition-all"
                  >
                    <Ambulance className="w-4 h-4" />
                    <span>Generate Service ID & Sync with Referral Network</span>
                  </button>
                </div>
              ) : (
                <div className="flex items-center justify-between pt-2">
                  <button
                    type="button"
                    onClick={() => setIsReferring(true)}
                    className="px-4 py-2.5 rounded-xl border border-purple-300 bg-purple-50 text-purple-800 hover:bg-purple-100 font-bold text-xs flex items-center space-x-1.5 transition-colors"
                  >
                    <Hospital className="w-4 h-4 text-purple-600" />
                    <span>Escalate to CHC / District Referral</span>
                  </button>

                  <button
                    type="button"
                    onClick={handleSaveConsultation}
                    className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center space-x-2 shadow-md shadow-emerald-700/20 active:scale-95 transition-all"
                  >
                    <CheckCircle2 className="w-4 h-4" />
                    <span>Complete Consultation & Issue Rx</span>
                  </button>
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-16 text-slate-400 text-xs">
              Select a patient from the queue to start consultation.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
